title: Doublem.org
author: Jerry Ahn
description: This is Doublem.org wiki.

highlighter: null
permalink: /:title

url: doublem.org
baseurl: doublem.org

# Custom options:
# color_scheme: azul|ruby|amber|avocado
 color_scheme: ruby
